version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bv-mysql
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bv-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 30s
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: bv-backend
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./app/static:/app/app/static
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bv-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local

networks:
  bv-network:
    driver: bridge
