"""add_video_view_tracking

Revision ID: 282d87587006
Revises: 7b029d1d8418
Create Date: 2025-09-06 16:14:24.673987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '282d87587006'
down_revision: Union[str, Sequence[str], None] = '7b029d1d8418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_view_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'video_id', name='unique_session_video')
    )
    op.create_index(op.f('ix_video_view_sessions_id'), 'video_view_sessions', ['id'], unique=False)
    op.alter_column('files', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('floorplan_analyses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # Skip the problematic file_data column change
    # op.alter_column('media_assets', 'file_data',
    #            existing_type=mysql.LONGBLOB(),
    #            type_=sa.LargeBinary(),
    #            existing_nullable=True)
    op.add_column('videos', sa.Column('view_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'view_count')
    # Skip the problematic file_data column change
    # op.alter_column('media_assets', 'file_data',
    #            existing_type=sa.LargeBinary(),
    #            type_=mysql.LONGBLOB(),
    #            existing_nullable=True)
    op.alter_column('floorplan_analyses', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('files', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_video_view_sessions_id'), table_name='video_view_sessions')
    op.drop_table('video_view_sessions')
    # ### end Alembic commands ###
