"""add_multiple_files_support

Revision ID: 56a319457db3
Revises: d09b8fc44508
Create Date: 2025-09-29 16:11:46.021645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56a319457db3'
down_revision: Union[str, Sequence[str], None] = 'd09b8fc44508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('books', sa.Column('pdf_url', sa.String(length=500), nullable=True))
    op.add_column('books', sa.Column('pdf_urls', sa.JSON(), nullable=True))
    # Skip file_data column modification to avoid data truncation issues
    # op.alter_column('media_assets', 'file_data',
    #            existing_type=mysql.LONGBLOB(),
    #            type_=sa.LargeBinary(),
    #            existing_nullable=True)
    op.add_column('vastu_tips', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.add_column('vastu_tips', sa.Column('descriptions', sa.JSON(), nullable=True))
    op.alter_column('vastu_tips', 'image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True)
    op.add_column('videos', sa.Column('video_urls', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'thumbnail_urls')
    op.drop_column('videos', 'video_urls')
    op.alter_column('vastu_tips', 'image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False)
    op.drop_column('vastu_tips', 'descriptions')
    op.drop_column('vastu_tips', 'image_urls')
    # Skip file_data column modification to avoid data truncation issues
    # op.alter_column('media_assets', 'file_data',
    #            existing_type=sa.LargeBinary(),
    #            type_=mysql.LONGBLOB(),
    #            existing_nullable=True)
    op.drop_column('books', 'pdf_urls')
    op.drop_column('books', 'pdf_url')
    op.drop_column('books', 'image_urls')
    # ### end Alembic commands ###
