"""fix_file_data_column_size

Revision ID: 8c246282c4fd
Revises: b71ed9307d22
Create Date: 2025-08-20 18:32:34.568339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '8c246282c4fd'
down_revision: Union[str, Sequence[str], None] = 'b71ed9307d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Change file_data column from BLOB to LONGBLOB to support larger files
    op.alter_column('media_assets', 'file_data',
               existing_type=mysql.BLOB(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Change file_data column back from LONGBLOB to BLOB
    op.alter_column('media_assets', 'file_data',
               existing_type=mysql.LONGBLOB(),
               type_=mysql.BLOB(),
               existing_nullable=True)
    
    # ### end Alembic commands ###
