"""Add image_data to floorplan_analyses

Revision ID: 8fdae89d78f4
Revises: 8c246282c4fd
Create Date: 2025-08-23 19:06:10.471164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fdae89d78f4'
down_revision: Union[str, Sequence[str], None] = '8c246282c4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floorplan_analyses', sa.Column('image_data', sa.LargeBinary(), nullable=False))
    op.alter_column('floorplan_analyses', 'original_image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True)
    op.alter_column('media_assets', 'file_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_assets', 'file_data',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('floorplan_analyses', 'original_image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False)
    op.drop_column('floorplan_analyses', 'image_data')
    # ### end Alembic commands ###
