"""add url column to videos

Revision ID: add_url_column_to_videos
Revises: 5230a667d509
Create Date: 2025-01-13 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_url_column_to_videos'
down_revision = '5230a667d509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'url')
    # ### end Alembic commands ###
