"""fix_videos_table_structure

Revision ID: b71ed9307d22
Revises: b8c941481890
Create Date: 2025-08-20 18:13:49.814844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'b71ed9307d22'
down_revision: Union[str, Sequence[str], None] = 'b8c941481890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add missing columns to videos table
    op.add_column('videos', sa.Column('title', sa.String(255), nullable=False))
    op.add_column('videos', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('videos', sa.Column('video_type', sa.String(50), nullable=True, server_default='blob'))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(500), nullable=True))
    op.add_column('videos', sa.Column('duration', sa.String(20), nullable=True))
    op.add_column('videos', sa.Column('views', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('videos', sa.Column('category', sa.String(100), nullable=True))
    op.add_column('videos', sa.Column('is_published', sa.Boolean(), nullable=True, server_default='1'))
    op.add_column('videos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove columns from videos table
    op.drop_column('videos', 'updated_at')
    op.drop_column('videos', 'created_at')
    op.drop_column('videos', 'is_published')
    op.drop_column('videos', 'category')
    op.drop_column('videos', 'views')
    op.drop_column('videos', 'duration')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'video_type')
    op.drop_column('videos', 'description')
    op.drop_column('videos', 'title')
    
    # ### end Alembic commands ###
