"""Initial schema

Revision ID: b8c941481890
Revises: 
Create Date: 2025-08-17 13:56:37.208771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b8c941481890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('file_data', sa.LargeBinary(), nullable=True))
    op.alter_column('media_assets', 'filename',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.alter_column('media_assets', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True)
    op.drop_column('videos', 'url')
    op.drop_column('videos', 'youtube_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('youtube_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.add_column('videos', sa.Column('url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=False))
    op.alter_column('media_assets', 'file_path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False)
    op.alter_column('media_assets', 'filename',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('media_assets', 'file_data')
    # ### end Alembic commands ###
